nama : UPCREW

aktif : workflow_dispatch

pekerjaan :

  membangun :

    run-on : windows-terbaru

    batas waktu-menit : 9999

    langkah :

    - nama : Unduh ngrok.

      lari : |

        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

        Invoke-WebRequest https://raw.githubusercontent.com/amineelkhayari/free_rdp/main/mulai.bat -OutFile mulai.bat

        Invoke-WebRequest https://raw.githubusercontent.com/amineelkhayari/free_rdp/main/up.bat -OutFile up.bat

        Invoke-WebRequest https://raw.githubusercontent.com/amineelkhayari/free_rdp/main/looping.bat -OutFile looping.bat

    - nama : Mengextrak File Ngrok.

      jalankan : Perluas-Arsip ngrok.zip

    - nama : Hubungkan ke ngrok.

      jalankan : .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env :

        NGROK_AUTH_TOKEN : ${{ rahasia.NGROK_AUTH_TOKEN }}

    - name : Mengunduh anydesk.

      lari : |

        Invoke-WebRequest https://download.anydesk.com/AnyDesk.exe -OutFile Anydesk.exe

      env :

        NGROK_AUTH_TOKEN : ${{ rahasia.NGROK_AUTH_TOKEN }}

    - nama : Mencoba Akses ke RDP.

      lari : |

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-nama "fDenyTSConnections" -Nilai 0

        Aktifkan-NetFirewallRule -DisplayGroup "Remote Desktop"

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -nama "UserAuthentication" -Nilai 1

        salin Anydesk.exe C:\Users\Public\Desktop\Anydesk.exe

    - nama : Membuat Sambungan.

      jalankan : Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'

    - nama : Menyambungkan Ke RDP.

      jalankan : cmd /c mulai.bat

    - nama : Sukses! Coba Kalian login ke RDP.

      jalankan : cmd /c looping.bat
